### ISSUE TITLE
Programing via USB instead of SD?

### ISSUE THREAD

**Issue by drphil3d** [bigtreetech/BIGTREETECH-SKR-mini-E3#196]
I would like to see if anyone has had luck with programming the SKR mini e3 via usb, I tried using flymcu but it doesn't seem to work sense it doesn't have a usb to serial chip just direct usb to the STM32. I'm not sure if the programming usb port on the STM32 is exposed or not. I'm designing an adapter kit to put this board in old printrbots with the least amount of modification. I have the choice of the USB or SD card being easy to access. 
![image](https://user-images.githubusercontent.com/21151734/76809222-6468a380-67a7-11ea-98df-a57934be548f.png)

This board uses a CH340 which makes it possible to program via usb easily. 
 https://wiki.fysetc.com/Cheetah_Board/

**Comment by B0M0A0K** [comment]
I have tried for quite some time to get my SKR-Mini-E3 to talk to VSC or even an Octopi without any success. As far as I am aware this is a MAJOR limitation of this board. It's very strange because I can talk to the board using USB via Pronterface, just not VSC/PlatformIO. I don't know if this is something that Bigtreetech could fix via firmware update, but I don't think they are interested and have moved on to their latest and greatest board. It's a shame because this and not being able to connect to Octopi for control are the two main things that let this board down.

**Comment by drphil3d** [comment]
you just didn't set the serial port config correctly in marlin. It looks like the STM32 would need a different bootloader or serial programmer which is what the Cheetah uses.

**Comment by dziabi3** [comment]
I send gocd from Octoprin to the SD carriage.
Initially I had problems but when I turned off the AUTO_REPORT_TEMPERATURES option, the write errors disappeared.

**Comment by drphil3d** [comment]
That's true huh, you could just leave the SD card plugged in and upload the new firmware.bin file to the sd card and power cycle...But the only problem is, if for some reason you accidently flash incorrect firmware or leave out the host drive feature... well then if the sd card slot is hard to access you're going to be taking things apart.
