### ISSUE TITLE
[BUG] Bed leveling doesn't happen automatically.

### ISSUE THREAD

**Issue by Doelfke** [bigtreetech/BIGTREETECH-SKR-mini-E3#368]
The bltouch-firmware _might_ work okay, but the x offset for the probe is too small, since I have a custom made head.

So I tried compiling my own, and managed to get it to work, sort of.  The BLTouch goes through it's test just fine, I see the options for the BLTouch in the menu, but when I try to level the board, it tries to manually, instead of automatically.

I've tried setting AUTO_BED_LEVELING_LINEAR, but it doesn't seem to make a difference.

**Comment by brew99** [comment]
If I understand what you are describing, it is acting as it should.   The menu items for BLtouch are for running it manually (i.e. it goes to a point, then you adjust your bed level via the adjustment wheels, moves to next, adjust and so on).   I use AUTO_BED_LEVELING_BILINEAR in the config.

You then should put the G29 (auto bed level probing) in your slicer, so that it is activated before each print and then uses the data to adjust your Z as it is printing
